### ISSUE TITLE
Bridge between Zeppelin and Zeppelin-Grunt

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/zeppelin-grunt#1]
How do you plan to manage the differences between Zeppelin and Zeppelin-Grunt.

There are features and bug fixes developed for Zeppelin. There are couple of new features in the Android Developer Days Ankara website. Do you plan to merge all of them here?

Thank you.

**Comment by ozasadnyy** [comment]
I am trying to keep the same core in both projects. And for sure I will add features from ADD site.
