### ISSUE TITLE
SVG Icons don't show on IE 11

### ISSUE THREAD

**Issue by johanbove** [gdg-x/zeppelin-grunt#5]
IE does not yet support [external SVG spritemaps](http://css-tricks.com/svg-sprites-use-better-icon-fonts/##Browser%20Support) and therefore the social-media icons and the "icon-arrow-down" SVG image won't show up.

I would like to include "[svg4everybody](https://github.com/jonathantneal/svg4everybody)" to the site to fix this.

**Comment by ozasadnyy** [comment]
Fixed with #6
